### ISSUE TITLE
libconfig9 not available

### ISSUE THREAD

**Issue by craiglund** [browndeer/coprthr#5]
The prototype Parallella systems are distributed with SSD cards containing Linaro Ubuntu 12.03. It is based on Ubuntu 11.10 oneiric. 

That OS ships with libconfig8. The newer libconfig9 is not available. Your test suite requires libconfig9.

Either you need to use 8 or Adapteva needs to ship a newer OS.

**Comment by browndeer** [comment]
If libconfig8 corresponds to libconfig-1.4.8 then there should be no issue.  We test using builds from source for the few package dependencies like libconfig since this is more consistent across the many platforms we test on.  We will try to varify OS specific versions available by default in the future.

**Comment by browndeer** [comment]
Just a follow-up on the issue of libconfig8/9.  These appear to correspond to version 0.8 and 0.9 of the software, and they should NOT be used.  They are ancient, and it can be confirmed that libconfig8 will not work.  You must use a current version, libconfig-1.4.8 or later.
